package com.abhinav.otapulse.catalog

import com.abhinav.otapulse.catalog.model.PredefinedDevice
import com.abhinav.otapulse.catalog.provider.DeviceProvider
import com.abhinav.otapulse.catalog.provider.oneplus.*
import com.abhinav.otapulse.catalog.provider.oppo.*
import com.abhinav.otapulse.catalog.provider.realme.*

/**
 * Aggregates all built-in device providers into a single catalog.
 *
 * Keeping this registry separate from generic helpers makes it much easier to
 * maintain the supported-device list as the app grows.
 */
object DeviceCatalog {

    private val deviceProviders: List<DeviceProvider> = listOf(
        // OnePlus devices
        OnePlus15RAce6T(),
        OnePlus15(),
        OnePlus13s(),
        OnePlus13T(),
        OnePlus13RAce5(),
        OnePlus13(),
        OnePlus12RAce3(),
        OnePlus12(),
        OnePlus11RAce2(),
        OnePlus11(),
        OnePlus10TAcePro(),
        OnePlus10R80W(),
        OnePlus10R150W(),
        OnePlus10Pro(),
        OnePlusAce6(),
        OnePlusAce5Pro(),
        OnePlusAce3V(),
        OnePlusAce3Pro(),
        OnePlusAce2V(),
        OnePlusAce2Pro(),
        OnePlusAceRacingEdition(),
        OnePlusNordCE5(),
        OnePlusNordCE4Lite(),
        OnePlusNordCE4(),
        OnePlusNordCE3Lite(),
        OnePlusNordCE3(),
        OnePlusNord5(),
        OnePlusNord4(),
        OnePlusNord3(),
        OnePlusPadPro(),
        OnePlusPad2Pro(),
        OnePlusPad2(),
        OnePlusPad(),
        OnePlusOpen(),

        // Realme devices
        RealmeGT8Pro(),
        RealmeGT7T(),
        RealmeGT7Pro(),
        RealmeGT7(),
        RealmeGT6T6SE(),
        RealmeGT6(),
        RealmeGT5Pro(),
        RealmeGT5G(),
        RealmeGT5_240W(),
        RealmeGT5(),
        RealmeGT3Neo5(),
        RealmeGT2Pro(),
        RealmeGT2(),
        RealmeNeo7x(),
        RealmeNeo7Turbo(),
        RealmeNeo7SE(),
        RealmeNeo7(),
        RealmeGTNeo6SE(),
        RealmeGTNeo6(),
        RealmeGTNeo5SE(),
        RealmeGTNeo5240W(),
        RealmeGTNeo3_150W(),
        RealmeGTNeo3_80W(),
        RealmeGTNeo2T(),
        RealmeGTNeo2(),
        RealmeX7MaxGTNeo(),
        RealmeGTMasterEdition(),
        Realme16ProPlus(),
        Realme16Pro(),
        Realme15x5G(),
        Realme15T(),
        Realme15Pro(),
        Realme15_5G(),
        Realme14x_5G(),
        Realme14ProPlus(),
        Realme14Pro(),
        Realme14(),
        Realme13ProPlus(),
        Realme13Pro(),
        Realme13Plus_5G(),
        Realme13(),
        Realme12x(),
        Realme12ProPlus(),
        Realme12Pro(),
        Realme12Plus_5G(),
        Realme12(),
        Realme11x_5G(),
        Realme11Pro_5G(),
        Realme11ProPlus_5G(),
        Realme11_5G(),
        Realme10ProPlus(),
        Realme10Pro(),
        Realme10(),
        Realme9i_5G(),
        Realme9i(),
        Realme9ProPlus(),
        Realme9Pro5G_Q5(),
        Realme9_SD695_5G(),
        Realme9_5GSpeed(),
        Realme9_5G(),
        Realme9_4G(),
        Realme8s_5G(),
        Realme8i(),
        Realme8Pro(),
        Realme8_5G(),
        Realme8(),
        RealmeC67_5G(),
        RealmeC65_5G(),
        RealmeC63_5G(),
        RealmeC25s(),
        RealmeC25(),
        RealmeNarzoN55(),
        RealmeNarzo90x(),
        RealmeNarzo80x_5G(),
        RealmeNarzo80Pro_5G(),
        RealmeNarzo70x_5G(),
        RealmeNarzo70Turbo_5G(),
        RealmeNarzo70Pro(),
        RealmeNarzo70_5G(),
        RealmeNarzo60x_5G(),
        RealmeNarzo60Pro(),
        RealmeNarzo60(),
        RealmeNarzo50Pro(),
        RealmeNarzo50A(),
        RealmeNarzo50(),
        RealmeNarzo30_5G(),
        RealmeP4Power_5G(),
        RealmeP4Pro_5G(),
        RealmeP4x_5G(),
        RealmeP4_5G(),
        RealmeP3x_5G(),
        RealmeP3Ultra_5G(),
        RealmeP3Pro_5G(),
        RealmeP3_5G(),
        RealmeP2Pro_5G(),
        RealmeP1Speed_5G(),
        RealmeP1Pro_5G(),
        RealmeP1_5G(),

        // OPPO devices
        OPPOFindN3(),
    )

    val predefinedDevices: List<PredefinedDevice> by lazy {
        deviceProviders.flatMap { it.getDevices() }
    }
}
